name: flutter_class_project_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  fonts:
    - family: Doto
      fonts:
        - asset: assets/fonts/Doto-Regular.ttf
        - asset: assets/fonts/Doto-Bold.ttf
        - asset: assets/fonts/Doto-Thin.ttf

    - family: EduAUVICWANTPre
      fonts:
        - asset: assets/fonts/EduAUVICWANTPre-Bold.ttf
        - asset: assets/fonts/EduAUVICWANTPre-Medium.ttf
        - asset: assets/fonts/EduAUVICWANTPre-Regular.ttf
        - asset: assets/fonts/EduAUVICWANTPre-SemiBold.ttf

    - family: SixtyfourConvergence
      fonts:
        - asset: assets/fonts/SixtyfourConvergence-Regular.ttf

  assets:
    - assets/images/s1.jpg
    - assets/images/s2.jpg
    - assets/images/s3.jpg
    - assets/images/s4.jpg
    - assets/images/s5.jpg
    - assets/images/s6.jpg